apiVersion: v1
kind: Pod                # Type of Kubernetes resource
metadata:
  name: example
  labels:
    app: example-app
    type: front-end           # Name of the Kubernetes resource
spec:
  containers:
    - name: example-api
      image: vietnt/example-api:latest
      imagePullPolicy: Never
      ports:
        - name: http
          containerPort: 8080
      env:
        - name: ENV                             # Name of the environmental variable file to load
          value: local
        - name: HTTP_PORT
          value: "8080"
        - name: DATABASE
          value: "root:root@tcp(mysql:3306)/example?charset=utf8mb4&parseTime=True&loc=Local"