apiVersion: v1
kind: Service
metadata:
  name: example-service
spec:
  ports:
    - targetPort: 8080
      port: 8080
#      nodePort: 30008
  selector:
    app: example-service
    type: internal-service
#  type: NodePort
#  type: LoadBalancer
  type: ClusterIP
