apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:

  #The type property in the Service's spec determines how the service is exposed to the network. 
  #It changes where a Service is able to be accessed from. The possible types are ClusterIP, NodePort, and LoadBalancer
  #ClusterIP: you can't make requests to your Pods from outside the cluster!
  #NodePort: the service can handle requests that originate from outside the cluster.
  #LoadBalancer: The service becomes accessible externally through a cloud provider's load balancer functionality.

  # Expose the service on a static port on each node
  # so that we can access the service from outside the cluster 
  # type: NodePort
  type: ClusterIP
  
  # Three types of ports for a service
  # nodePort - a static port assigned on each the node
  # port - port exposed internally in the cluster
  # targetPort - the container port to send requests to

  ports:
    - port: 3306
      targetPort: 3306
      # nodePort: 30600

  # When the node receives a request on the static port (30600)
  # "select pods with the label 'app' set to 'echo-hostname'"
  # and forward the request to one of them
  selector:
    app: mysql
  #clusterIP: None