apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-test
spec:
  selector:
    matchLabels:
      app: mysql-test
  template:
    metadata:
      labels:
        app: mysql-test
    spec:
      containers:
      - name: mysql-test
        image: mysql:8.0
        env:
        - name: MYSQL_USER
          value: root
        - name: MYSQL_PASSWORD
          value: 123456
        - name: MYSQL_ROOT_PASSWORD
          value: root
        - name: MYSQL_DATABASE
          value: example
        ports:
        - containerPort: 3307
        volumeMounts:
        - name: mysql-test-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-test-persistent-storage
        emptyDir: {}
