apiVersion: v1
kind: Service
metadata:
  annotations: 
    cloud.google.com/backend-config: ''' { "ports": { {{ .Values.listenPort | quote }} : {{ include "app.fullname" . | quote }} } } '''
  name: {{ include "app.fullname" . }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "app.selectorLabels" . | nindent 4 }}
---
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: {{ include "app.fullname" . }}
spec:
  healthCheck:
    checkIntervalSec: 15
    port: {{ .Values.listenPort }}
    type: HTTP
    requestPath: {{ .Values.healtcheckPath }}