info:
  contact: {}
paths:
  /tasks:
    get:
      consumes:
      - application/json
      description: Do GetTasks
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: GetTasks example
      tags:
      - example
swagger: "2.0"
